application: appengine-example 
version: 1
runtime: java
public_root: /root

resource_files:
  - exclude: README.md 

handlers:
  - url: /*
    servlet: org.ringojs.jsgi.JsgiServlet
    name: ringo
    init_params:  
        module-path: src
        config: main
        app: app 
        optlevel: -1
        ringo-home: /
